# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('BOY', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_01.Boy')),
                ('Girl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_01.Girl')),
            ],
        ),
        migrations.AddField(
            model_name='boy',
            name='B2G',
            field=models.ManyToManyField(to='app_01.Girl'),
        ),
    ]
