# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='Girl',
            new_name='GIRL',
        ),
    ]
